---
abstract: 'Perform actions based upon file dependencies'
author:
  - 'The Smithsonian Astrophysical Observatory'
build_requires:
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.68'
license: gpl3
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Decision-Depends
no_index:
  directory:
    - inc
    - t
requires:
  Data::Compare: 0
  Tie::IxHash: 0
  YAML: 0
version: 0.18
